### ISSUE TITLE
some mistakes  in Kedacontoller spec examples in Readme.md

### ISSUE THREAD

**Issue by dudniksergei** [kedacore/keda-olm-operator#115]
## Expected Behavior
requests should be less or equal than limits in KedaConroller example.

## Actual Behavior
requests are more that limits 
```yaml
  ## Manage resource requests & limits for KEDA Operator
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  # resourcesKedaOperator:
  #   limits:
  #     cpu: 100m
  #     memory: 100Mi
  #   requests:
  #     cpu: 1000m
  #     memory: 1000Mi

  ## Manage resource requests & limits for KEDA Metrics Server
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  # resourcesMetricsServer:
  #   limits:
  #     cpu: 100m
  #     memory: 100Mi
  #   requests:
  #     cpu: 1000m
  #     memory: 1000Mi
```

## Steps to Reproduce the Problem

  1. use example resource definition
  2. keda contoller installation failed

## Specifications

  - **KEDA OLM Operator Version** *2.4.0*
  - **KEDA Version:** *2.4.0*
  - **Platform & Version:** *Openshft 4.7*
  - **Kubernetes Version:** *any* 
  - **OLM Version:** *any*

**Comment by zroubalik** [comment]
Good catch, thanks! It should be obviously the other way round. I am gonna fix this typo.
