### ISSUE TITLE
Utilizing AAD pod identity with KEDA when installing through OLM operator

### ISSUE THREAD

**Issue by kyschouv** [kedacore/keda-olm-operator#129]
There are clear instructions for how to enable and use AAD pod identity when [installing KEDA with the Helm chart](https://keda.sh/docs/2.3/concepts/authentication/#azure-pod-identity), but there don't seem to be any instructions for how to do so with the OLM operator. Is it possible? If not, it would be extremely useful to add that capability.

**Comment by zroubalik** [comment]
That's a valid ask. I think we can allow users to specify basically any labels/annotations on the deployed operator and metric server. We don't need to limit just to AAD pod idenitity.

@kyschouv is this something that you are willing to contribute?

**Comment by kyschouv** [comment]
I unfortunately don't know enough golang, nor do I have the time for a while. My team got tripped up trying to install and use KEDA, so I investigated and noticed it didn't seem possible to use AAD pod identity if we installed through OLM (which is our preferred way to manage operator installs).

**Comment by zroubalik** [comment]
@kyschouv okay, I might be able to nail this down, it should be relatively easy to support this. Is specifying labels/annotations the created service account something that you would need as well?

**Comment by kyschouv** [comment]
Ah, yes, I imagine we'll need that once we migrate off pod identity.

**Comment by zroubalik** [comment]
@kyschouv I pinged you on slack, would be great if you check it once you have a time
