### ISSUE TITLE
Operator needs a higher memory limit

### ISSUE THREAD

**Issue by StevenBarre** [kedacore/keda-olm-operator#162]
https://github.com/kedacore/keda-olm-operator/blob/5c02a15ec6ff19ee8aae7d5f71c5fb0b28ea98d0/config/manager/manager.yaml#L34

```
$ oc -n keda describe pod keda-olm-operator-5467bbb7b9-547p6 | grep -A10 'Last State'
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 03 Nov 2022 14:13:45 -0700
      Finished:     Thu, 03 Nov 2022 14:14:13 -0700
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
```

**Comment by StevenBarre** [comment]
I was able to edit the Deployment to increase the memory limit. But I assume the OLM might override/reset that at some point.

Memory on startup appears to peak just over 524Mi ?

![image](https://user-images.githubusercontent.com/24236108/199837953-580f296a-9d34-4307-a8aa-091c7d049ab9.png)

**Comment by zroubalik** [comment]
@StevenBarre make sense, would you mind opening a PR with more appropriate limits?
