### ISSUE TITLE
Keda Operator marked as Depricated in OKD 4.X

### ISSUE THREAD

**Issue by ffppmm** [kedacore/keda-olm-operator#211]
Hi,

we want to use Keda and have noticed that in OKD over the operator HUB it has been marked depricated 😞 

2.7.1 provided by KEDA Community is also a little out of date. Are there any plans to update to current Release?

We do not want to use the redhat auto Scaler operator.

Regards Philipp

**Comment by joelsmith** [comment]
Hi,
We have decided not to publish KEDA for OpenShift OCD and OKD given that Red Hat ships Custom Metrics Autoscaler instead. However, we do publish new versions of KEDA to the Kubernetes community operators. You can add their catalog to your cluster to be able to install the new KEDA OLM operator.

You will need to add a catalog source once as explained here:

https://github.com/k8s-operatorhub/community-operators
