### ISSUE TITLE
Openshift is stuck with KEDA v2.7.1

### ISSUE THREAD

**Issue by vku-ibm** [kedacore/keda-olm-operator#222]
This isn't a feature request but neither is an actual bug report, at least not with the operator itself.

Currently observing that Openshift instances on IBM Cloud and on AWS are pretty much stuck with KEDA v2.7.1, if operator is installed from the Hub. 
On a different cluster (on-prem) we deployed KEDA using helm, it's running KEDA 2.12.1 as expected.
Perhaps some note is needed in the readme to raise awareness that Hub installation can be problematic. Message on Hub does say (Depricated) but it was working just fine until the semi-recent kubernetes upgrade on the openshift.

With a manual install one needs to be aware that KEDA version have to be matched with a proper kubernetes versions, to avoid this:
```
xxxxx INFO setup Running on Kubernetes 1.25 {"version": "v1.25.16+a4e782e"}
xxxxx INFO setup WARNING: KEDA 2.12.1 hasn't been tested on Kubernetes v1.25.16+a4e782e
```
Found the link to the mapping:
https://keda.sh/docs/2.13/operate/cluster/

edit: we used helm for the on-prem deployment, not the operator

**Comment by joelsmith** [comment]
Red Hat no longer does KEDA releases in their catalog but does provide Custom Metrics Autoscaler, which is the downstream, Red Hat branded version of KEDA. If you don't want to run Custom Metrics Autoscaler but would like to run KEDA on OpenShift and deploy via the OLM operator, you should add the [Kubernetes Community Operators repo](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/#example---operatorhubio) as a catalog source, which will allow you to install the KEDA OLM operator.

**Comment by vku-ibm** [comment]
fyi

Viktor Kuropiatnyk
Software Engineer ? AI4K

IBM Research GmbH
S?umerstrasse 4
8803 R?schlikon
Switzerland




From: Joel Smith ***@***.***>
Date: Tuesday, 18 June 2024 at 21:31
To: kedacore/keda-olm-operator ***@***.***>
Cc: Viktor Kuropiatnyk ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [kedacore/keda-olm-operator] Openshift is stuck with KEDA v2.7.1 (Issue #222)
Red Hat no longer does KEDA releases in their catalog but does provide Custom Metrics Autoscaler, which is the downstream, Red Hat branded version of KEDA. If you don't want to run Custom Metrics Autoscaler but would like to run KEDA on OpenShift


Red Hat no longer does KEDA releases in their catalog but does provide Custom Metrics Autoscaler, which is the downstream, Red Hat branded version of KEDA. If you don't want to run Custom Metrics Autoscaler but would like to run KEDA on OpenShift and deploy via the OLM operator, you should add the Kubernetes Community Operators repo<https://olm.operatorframework.io/docs/concepts/crds/catalogsource/#example---operatorhubio> as a catalog source, which will allow you to install the KEDA OLM operator.

?
