### ISSUE TITLE
Please remove this constraint: KedaController resource needs to be created in namespace keda with name keda, otherwise it will be ignored

### ISSUE THREAD

**Issue by imriss** [kedacore/keda-olm-operator#90]
### Use-Case
I would like to use KEDA OLM Operator to deploy multiple KEDA controllers, each one monitoring one specific namespace.
However, when I tried it, it seems that it got ignored with the following error message in the OLM container logs:
```
The KedaController resource needs to be created in namespace keda with name keda, otherwise it will be ignored
```

### Specification
It seems that KEDA itself allows deployment in namespaces other than keda.
- [ ] Please remove the constraint if technically possible in order to allow having multiple KEDA controllers deployed in the same cluster.

**Comment by zroubalik** [comment]
Hi, currently it is not possible to run multiple KEDA instances, hence the constraint.

https://keda.sh/docs/2.3/operate/cluster/#high-availability

**Comment by imriss** [comment]
Hi @zroubalik , thanks
I am not interested to have HA for the controller (multiple replica for one controller).
Instead, I would like to deploy multiple controllers (each one would have only replicas=1, and would monitor a different namespace). 
It seems that this is possible (for example, https://github.com/kedacore/charts/pull/43, https://github.com/kedacore/charts/pull/43#issuecomment-616439559).
Thanks

**Comment by zroubalik** [comment]
Hi, yeah I understand your usecase. But as I mentioned it is not possible to run mutliple KEDA instances on one cluster at the moment. There is a limitation in the kuberenetes custom metrics library, that's being used by KEDA.

https://github.com/kedacore/keda/issues/470
